run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 3m

linters:
  enable:
    - deadcode
    - errcheck
    - gas
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosimple
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
  disable:
    - depguard
    - dupl
    - gocyclo
    - govet
    - interfacer
    - lll
    - maligned
    - prealloc
  fast: false
