version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # ignore forked linters because of their versioning issues. TODO: fix it.
      - dependency-name: "github.com/golangci/*"
    reviewers:
      - "golangci/team"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "golangci/team"
  - package-ecosystem: docker
    directory: "/build"
    schedule:
      interval: weekly
    reviewers:
      - "golangci/team"
