language: go
os: linux
dist: xenial
go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
jobs:
  include:
    - go: 1.x
      script:
        - make ci
      after_success:
        - bash <(curl -s https://codecov.io/bash)
script:
  - GO111MODULE=on make test
